export const puzzle = {
  CLEAR_PUZZLE_DATA: 'CLEAR_PUZZLE_DATA',
  GET_PUZZLE_DATA_SUCCESS: 'GET_PUZZLE_DATA_SUCCESS',
  GET_PUZZLE_DATA_FAILURE: 'GET_PUZZLE_DATA_FAILURE',
  SUBMIT_PUZZLE_DATA_SUCCESS: 'SUBMIT_PUZZLE_DATA_SUCCESS',
  SUBMIT_PUZZLE_DATA_FAILURE: 'SUBMIT_PUZZLE_DATA_FAILURE',
  SENDING_DATA: 'SENDING_DATA',
  FROM_CACHE: 'FROM_CACHE',
  FROM_MONGO: 'FROM_MONGO'
};

export const websocket = {
  CONNECT_TO_SOCKET: 'CONNECT_TO_SOCKET',
  DISCONNECT_FROM_SOCKET: 'DISCONNECT_FROM_SOCKET',
  GET_PODS: 'GET_PODS',
  POD_UP: 'POD_UP',
  POD_DOWN: 'POD_DOWN',
  ACTIVE_INSTANCE: 'ACTIVE_INSTANCE',
  SCALE: 'SCALE'
};
