node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "mointor-scale"
    registryHost = "127.0.0.1:30912/"
    imageName = "${registryHost}${appName}:${tag}"
    env.COMMITTAG=tag
    env.BUILDIMG=imageName

    stage "Build"
    
        sh "docker build -t ${imageName} applications/monitor"
    
    stage "Push"

        sh "docker push ${imageName}"

    stage "Deploy"

        sh "sed 's#__TAG__#'$COMMITTAG'#' applications/monitor/k8s/monitor-scale.yaml | kubectl apply -f -"
}