export const puzzle = {
  GET_PUZZLE_DATA_SUCCESS: 'GET_PUZZLE_DATA_SUCCESS',
  GET_PUZZLE_DATA_FAILURE: 'GET_PUZZLE_DATA_FAILURE',
  SUBMIT_PUZZLE_DATA_SUCCESS: 'SUBMIT_PUZZLE_DATA_SUCCESS',
  SUBMIT_PUZZLE_DATA_FAILURE: 'SUBMIT_PUZZLE_DATA_FAILURE',
  SENDING_DATA: 'SENDING_DATA'
};

export const websocket = {
  CONNECT: 'CONNECT',
  DATA_RECEIVED: 'DATA_RECEIVED',
  DISCONNECT: 'DISCONNECT'
};
