export const puzzle = {
  GET_PUZZLE_DATA_SUCCESS: 'GET_PUZZLE_DATA_SUCCESS',
  GET_PUZZLE_DATA_FAILURE: 'GET_PUZZLE_DATA_FAILURE',
  SUBMIT_PUZZLE_DATA_SUCCESS: 'SUBMIT_PUZZLE_DATA_SUCCESS',
  SUBMIT_PUZZLE_DATA_FAILURE: 'SUBMIT_PUZZLE_DATA_FAILURE',
  SENDING_DATA: 'SENDING_DATA',
  FROM_CACHE: 'FROM_CACHE',
  FROM_MONGO: 'FROM_MONGO'
};

export const websocket = {
  CONNECT: 'CONNECT',
  DATA_RECEIVED: 'DATA_RECEIVED',
  DISCONNECT: 'DISCONNECT'
};
