export const puzzle = {
  GET_PUZZLE_DATA: 'GET_PUZZLE_DATA',
  SUBMIT_PUZZLE_DATA: 'SUBMIT_PUZZLE_DATA'
};

export const websocket = {
  CONNECT: 'CONNECT',
  DATA_RECEIVED: 'DATA_RECEIVED',
  DISCONNECT: 'DISCONNECT'
};
